version: '2'

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - 8080:80
